version: '3.8'
services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/usr/src/myapp
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    network_mode: host

  pgdb:

    image: postgres
    ports:
      - "5432:5432"
    env_file: .env
    environment:
         - POSTGRES_DB=${NAME}
         - POSTGRES_USER=${USER}
         - POSTGRES_PASSWORD=${PASSWORD}
    container_name: pgdb
