# Generated by Django 5.1.7 on 2025-03-27 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packagetype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('мелкий пакет', 'мелкий пакет'), ('посылка', 'посылка'), ('посылка 1 класса', 'посылка 1 класса'), ('ценная посылка', 'ценная посылка'), ('посылка международная', 'посылка международная'), ('экспресс-посылка', 'экспресс-посылка')], max_length=50, verbose_name='Тип посылки')),
            ],
            options={
                'verbose_name': 'Тип посылок',
                'verbose_name_plural': 'Тип посылки',
                'db_table': 'Packagetype',
            },
        ),
        migrations.CreateModel(
            name='Typeofletter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('письмо', 'письмо'), ('заказное письмо', 'заказное письмо'), ('ценное письмо', 'ценное письмо'), ('экспресс-письмо', 'экспресс-письмо')], max_length=20, verbose_name='Тип письма')),
            ],
            options={
                'verbose_name': 'Тип писем',
                'verbose_name_plural': 'Тип письма',
                'db_table': 'Typeofletter',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=100, verbose_name='ФИО отправиеля')),
                ('recipient', models.CharField(max_length=100, verbose_name='Фио получателя')),
                ('sending', models.CharField(max_length=100, verbose_name='Пункт отправки')),
                ('receiving', models.CharField(max_length=100, verbose_name='Пункт получения')),
                ('senders_index', models.CharField(max_length=6, verbose_name='Индекс места отправителя')),
                ('recipients_index', models.CharField(max_length=6, verbose_name='Индекс места получателя')),
                ('package_weight', models.FloatField(default=0, verbose_name='Вес посылки')),
                ('package_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.packagetype', verbose_name='Тип письма')),
            ],
            options={
                'verbose_name': 'Посылки',
                'verbose_name_plural': 'Посылка',
                'db_table': 'Package',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=100, verbose_name='ФИО отправиеля')),
                ('recipient', models.CharField(max_length=100, verbose_name='Фио получателя')),
                ('sending', models.CharField(max_length=100, verbose_name='Пункт отправки')),
                ('receiving', models.CharField(max_length=100, verbose_name='Пункт получения')),
                ('senders_index', models.CharField(max_length=6, verbose_name='Индекс места отправителя')),
                ('recipients_index', models.CharField(max_length=6, verbose_name='Индекс места получателя')),
                ('letter_weight', models.FloatField(default=0, verbose_name='Вес письма')),
                ('type_of_letter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typeofletter', verbose_name='Тип письма')),
            ],
            options={
                'verbose_name': 'Письма',
                'verbose_name_plural': 'Письмо',
                'db_table': 'Letter',
            },
        ),
    ]
