# Generated by Django 5.1.7 on 2025-03-26 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=100, verbose_name='ФИО отправиеля')),
                ('recipient', models.CharField(max_length=100, verbose_name='Фио получателя')),
                ('sending', models.CharField(max_length=100, verbose_name='Пункт отправки')),
                ('receiving', models.CharField(max_length=100, verbose_name='Пункт получения')),
                ('senders_index', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(6)], verbose_name='Индекс места отправителя')),
                ('recipients_index', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(6)], verbose_name='Индекс места получателя')),
                ('letter_weight', models.FloatField(default=0, verbose_name='Вес письма')),
                ('typeofletter', models.CharField(choices=[('1', 'письмо,'), ('2', 'заказное письмо'), ('3', 'ценное письмо'), ('4', 'экспресс-письмо')], max_length=20, verbose_name='Тип письма')),
            ],
            options={
                'verbose_name': 'Письма',
                'verbose_name_plural': 'Письмо',
                'db_table': 'Letter',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=100, verbose_name='ФИО отправиеля')),
                ('recipient', models.CharField(max_length=100, verbose_name='Фио получателя')),
                ('sending', models.CharField(max_length=100, verbose_name='Пункт отправки')),
                ('receiving', models.CharField(max_length=100, verbose_name='Пункт получения')),
                ('senders_index', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(6)], verbose_name='Индекс места отправителя')),
                ('recipients_index', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(6)], verbose_name='Индекс места получателя')),
                ('package_weight', models.FloatField(default=0, verbose_name='Вес посылки')),
                ('package_type', models.CharField(choices=[('1', 'мелкий пакет'), ('2', 'посылка,'), ('3', 'посылка 1 класса'), ('4', 'ценная посылка'), ('5', 'посылка международная,'), ('6', 'экспресс-посылка')], max_length=20, verbose_name='Тип посылки')),
            ],
            options={
                'verbose_name': 'Посылки',
                'verbose_name_plural': 'Посылка',
                'db_table': 'Package',
            },
        ),
    ]
