# Generated by Django 5.1.7 on 2025-03-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тип посылки'),
        ),
        migrations.AlterField(
            model_name='typeofletter',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тип письма'),
        ),
    ]
