# Generated by Django 5.1.7 on 2025-03-26 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='recipients_index',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(999), django.core.validators.MaxValueValidator(999999)], verbose_name='Индекс места получателя'),
        ),
    ]
