# Generated by Django 5.1.7 on 2025-03-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_letter_senders_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='typeofletter',
            field=models.CharField(choices=[('письмо', 'письмо'), ('заказное письмо', 'заказное письмо'), ('ценное письмо', 'ценное письмо'), ('экспресс-письмо', 'экспресс-письмо')], max_length=20, verbose_name='Тип письма'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('мелкий пакет', 'мелкий пакет'), ('посылка', 'посылка'), ('посылка 1 класса', 'посылка 1 класса'), ('ценная посылка', 'ценная посылка'), ('посылка международная', 'посылка международная'), ('экспресс-посылка', 'экспресс-посылка')], max_length=50, verbose_name='Тип посылки'),
        ),
    ]
