# Generated by Django 5.1.7 on 2025-03-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_letter_typeofletter_alter_package_package_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packagetype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('мелкий пакет', 'мелкий пакет'), ('посылка', 'посылка'), ('посылка 1 класса', 'посылка 1 класса'), ('ценная посылка', 'ценная посылка'), ('посылка международная', 'посылка международная'), ('экспресс-посылка', 'экспресс-посылка')], max_length=50, verbose_name='Тип посылки')),
            ],
            options={
                'verbose_name': 'Тип посылок',
                'verbose_name_plural': 'Тип посылки',
                'db_table': 'Packagetype',
            },
        ),
        migrations.CreateModel(
            name='Typeofletter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[(1, 'письмо'), (2, 'заказное письмо'), (3, 'ценное письмо'), (4, 'экспресс-письмо')], max_length=20, verbose_name='Тип письма')),
            ],
            options={
                'verbose_name': 'Тип писем',
                'verbose_name_plural': 'Тип письма',
                'db_table': 'Typeofletter',
            },
        ),
        migrations.RemoveField(
            model_name='letter',
            name='typeofletter',
        ),
        migrations.RemoveField(
            model_name='package',
            name='package_type',
        ),
        migrations.AddField(
            model_name='package',
            name='type_of_letter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.packagetype', verbose_name='Тип письма'),
        ),
        migrations.AddField(
            model_name='letter',
            name='type_of_letter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.typeofletter', verbose_name='Тип письма'),
        ),
    ]
