# Generated by Django 5.1.7 on 2025-03-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_letter_typeofletter_package_package_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='type_of_letter',
        ),
        migrations.RemoveField(
            model_name='package',
            name='type_of_letter',
        ),
    ]
