# Generated by Django 5.1.7 on 2025-03-26 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_letter_type_of_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='typeofletter',
        ),
        migrations.AddField(
            model_name='letter',
            name='type_of_letter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.typeofletter', verbose_name='Тип письма'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.packagetype', verbose_name='Тип письма'),
        ),
        migrations.AlterField(
            model_name='typeofletter',
            name='name',
            field=models.CharField(choices=[('письмо', 'письмо'), ('заказное письмо', 'заказное письмо'), ('ценное письмо', 'ценное письмо'), ('экспресс-письмо', 'экспресс-письмо')], max_length=20, verbose_name='Тип письма'),
        ),
    ]
